#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --partition={QUEUE}

#SBATCH --time={WALLTIME}

#SBATCH --mail-type=END
#SBATCH --mail-user=fverdian@sissa.it
#SBATCH --cpus-per-task={OMP}
#SBATCH --output=/home/fverdian/cobaya/Slurm-output/{INIBASE}.log
export OMP_NUM_THREADS=$(({OMP}/2))
export RDMAV_FORK_SAFE=1
export PYTHONUNBUFFERED=1

###set things to be used by the python script, which extracts text from here with ##XX: ... ##
### command to use for each run in the batch
##RUN: {PROGRAM} {INI}##
### defaults for this script
##DEFAULT_qsub: sbatch ##
##DEFAULT_qdel: scancel ##
##DEFAULT_nodes: 1 ##
##DEFAULT_cores_per_node: 64 ##
##DEFAULT_chains_per_node: 1 ##
##DEFAULT_program: cobaya-run -r ##
##DEFAULT_walltime: 11:59:00 ##
##DEFAULT_queue: gpu2##
{COMMAND}

wait



