site_name: PBJ - Power spectrum & Bispectrum Joint analysis

nav:
  - index.md
  - Getting started: getting_started.md
  - Theoretical Prediction:
    - Power spectrum: power_spectrum.md
    - Bispectrum: bispectrum.md
  - Bayesian Inference:
    - paramfile.md
    - inputs.md
    - likelihood.md
    - priors.md
    - samplers.md
    - outputs.md
  - Multiple redshift bins:
      - multiz.md
  - Examples:
    - examples_theory.md
    - examples_likelihood.md
  - API:
    - PBJ: pbj_api.md
    - likelihoodPBJ: likelihood_api.md

theme:
  favicon: img/PBJ4.png
  features:
    - content.code.annotate
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  icon:
    repo: fontawesome/brands/gitlab
  logo: img/PBJ4.png
  name: "material"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: lime

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: deep orange


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2


extra_css:
  - css/material.css
  - css/mkdocstrings.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://gitlab.com/chiaramoretti/pbj
repo_name: chiaramoretti/pbj
copyright: Copyright &copy; 2022 - 2025 Chiara Moretti
